#pragma once

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    EB_CTRL_VOL = 0,
    EB_CTRL_SQL,
    EB_CTRL_RFG,
    EB_CTRL_FILTER_LOW,
    EB_CTRL_FILTER_HIGH,
    EB_CTRL_PWR,
    EB_CTRL_HMIC,
    EB_CTRL_MIC,
    EB_CTRL_IMIC,
    EB_CTRL_MONI,
    EB_CTRL_FILTER_BW,

    EB_CTRL_SPECTRUM_FACTOR,

    EB_CTRL_KEY_SPEED,
    EB_CTRL_KEY_MODE,
    EB_CTRL_IAMBIC_MODE,
    EB_CTRL_KEY_TONE,
    EB_CTRL_KEY_VOL,
    EB_CTRL_KEY_TRAIN,
    EB_CTRL_QSK_TIME,
    EB_CTRL_KEY_RATIO,

    EB_CTRL_DNF,
    EB_CTRL_DNF_CENTER,
    EB_CTRL_DNF_WIDTH,
    EB_CTRL_DNF_AUTO,
    EB_CTRL_NB,
    EB_CTRL_NB_LEVEL,
    EB_CTRL_NB_WIDTH,
    EB_CTRL_NR,
    EB_CTRL_NR_LEVEL,

    EB_CTRL_AGC_HANG,
    EB_CTRL_AGC_KNEE,
    EB_CTRL_AGC_SLOPE,
    EB_CTRL_COMP,

    EB_CTRL_CW_DECODER,
    EB_CTRL_CW_TUNE,
    EB_CTRL_CW_DECODER_SNR,
    EB_CTRL_CW_DECODER_PEAK_BETA,
    EB_CTRL_CW_DECODER_NOISE_BETA,

    EB_CTRL_ANT,
    EB_CTRL_RIT,
    EB_CTRL_XIT,
    EB_CTRL_IF_SHIFT,

    EB_CTRL_VOX_ON,
    EB_CTRL_VOX_GAIN,
    EB_CTRL_VOX_AG,
    EB_CTRL_VOX_DELAY,

    EB_CTRL_CW_PEAK_ON,
    EB_CTRL_CW_PEAK_Q,
    EB_CTRL_CW_ZAP,

    EB_CTRL_FAST_ACCESS_LAST,

    /* APPs */

    EB_CTRL_RTTY_RATE,
    EB_CTRL_RTTY_SHIFT,
    EB_CTRL_RTTY_CENTER,
    EB_CTRL_RTTY_REVERSE,

    EB_CTRL_LAST,
} eb_ctrl_t;

typedef enum {
    EB_BIND_NONE = '_',
    EB_BIND_VOL  = 'V',
    EB_BIND_MFK  = 'M'
} eb_bind_t;

#ifdef __cplusplus
}
#endif
