#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <time.h>

typedef enum {
    // "CQ CALL ..." or "CQ DX CALL ..." or "CQ EU CALL ..."
    FTX_MSG_TYPE_CQ,
    // "CALL1 CALL2 GRID"
    FTX_MSG_TYPE_GRID,
    // "CALL1 CALL2 +1"
    FTX_MSG_TYPE_REPORT,
    // "CALL1 CALL2 R+1"
    FTX_MSG_TYPE_R_REPORT,
    // "CALL1 CALL2 RR73"
    FTX_MSG_TYPE_RR73,
    // "CALL1 CALL2 73"
    FTX_MSG_TYPE_73,

    FXT_MSG_TYPE_OTHER,
} ftx_msg_type_t;

typedef struct {
    char           grid[9];
    char           call_de[13];
    int            local_snr;
    int            remote_snr;
    bool           to_me;
    float          freq_hz;
    float          time_sec;
    ftx_msg_type_t type;
} ftx_msg_meta_t;

typedef struct {
    char msg[35];
    int  repeats;
} ftx_tx_msg_t;

/* Engine behaviour level (the "Auto" button): how far the engine may go
 * on its own. OFF replies only within the QSO armed by a user click; the
 * other levels run the ft8d auto pipeline with a widening candidate pool. */
typedef enum {
    FTX_QSO_AUTO_OFF = 0,
    /* Answer stations calling me, never initiate (no answering other CQs,
     * no tail-ending). The CQ loop runs on this level. */
    FTX_QSO_AUTO_RES,
    /* Also answer other stations' CQs, but no tail-ending. */
    FTX_QSO_AUTO_FULL,
    /* Preemptive: additionally tail-end stations freed by a RR73/73. */
    FTX_QSO_AUTO_PRE,
} ftx_qso_auto_t;

/* Tie-break (the "Auto Mode" button) used when several candidates share
 * the best QSO progress. NEW_GRID prefers grids not worked yet, then
 * picks at random. */
typedef enum {
    FTX_QSO_SEL_SNR = 0,
    FTX_QSO_SEL_DISTANCE,
    FTX_QSO_SEL_RANDOM,
    FTX_QSO_SEL_NEW_GRID,
} ftx_qso_sel_t;

typedef struct {
    const char    *local_callsign;
    const char    *local_qth;
    ftx_qso_auto_t auto_level;
    ftx_qso_sel_t  sel;
    /* Wall clock of the call (the engine itself never reads the clock);
     * used for QSO start/end timestamps. */
    time_t         now;
} ftx_qso_context_t;

typedef struct {
    const char *text;
    int         snr;
    float       freq_hz;
    float       time_sec;
    bool        odd;
    /* Logbook flags filled by the caller (the engine never touches the
     * database). worked: this station (call + grid tuple) was already
     * worked on the current band/mode from the current grid — auto modes
     * won't initiate a new QSO with it (replies to it keep working).
     * grid_worked: the sender's grid was worked already (unknown grid
     * counts as worked); drives the NEW_GRID tie-break. */
    bool        worked;
    bool        grid_worked;
} ftx_decoded_msg_t;

typedef enum {
    FTX_QSO_ACTION_RX = 0,
    FTX_QSO_ACTION_TX,
} ftx_qso_action_t;

/* A completed QSO ready for the logbook. rst_sent is the report we actually
 * transmitted to the peer (matches the peer's log); rst_rcvd is the report
 * the peer gave us. */
typedef struct {
    char   call[13];
    char   grid[9];
    int    rst_sent;
    int    rst_rcvd;
    time_t start_time;
    time_t end_time;
} ftx_qso_record_t;

/* Engine output for exactly one upcoming slot. The caller transmits tx_msg
 * once in the next slot of tx_odd parity and then waits for the next engine
 * response; any retry/repeat policy lives inside the engine.
 *
 * `save` is independent of `action`: a QSO can complete on a received
 * final 73 with no reply scheduled (action stays RX). */
typedef struct {
    ftx_qso_action_t action;
    bool  tx_odd;
    char  tx_msg[35];
    /* Peer frequency for finder cursor / QSY; 0 = keep current. */
    float freq_hz;

    bool             save;
    ftx_qso_record_t qso;
} ftx_qso_response_t;

#ifdef __cplusplus
#include <string>
#include <vector>

std::vector<std::string> split_text(std::string text);

extern "C" {
#endif

void ftx_qso_parse_rx_text(const ftx_qso_context_t *ctx,
                           const char *text, int snr,
                           float freq_hz, float time_sec,
                           ftx_msg_meta_t *meta);

/* Slot-end entry: the complete decoded batch of the slot that just ended
 * (msg_count may be 0 — an empty slot is itself a signal). */
void ftx_qso_on_decoded_messages(const ftx_qso_context_t *ctx,
                                 const ftx_decoded_msg_t *msgs,
                                 size_t msg_count,
                                 bool rx_odd,
                                 ftx_qso_response_t *response);

/* User-click entry: a signal that arms the manual QSO state (target
 * callsign + parity lock + sticky seed) and immediately evaluates the
 * clicked message as a batch of one. Timing (TX window) is the caller's
 * concern; a missed response is regenerated by the sticky retry. */
void ftx_qso_on_user_message(const ftx_qso_context_t *ctx,
                             const char *text,
                             int snr,
                             float freq_hz,
                             bool rx_odd,
                             ftx_qso_response_t *response);

/* Pop every complete-but-unclosed QSO out of the peers ledger: both
 * reports exchanged but the final RR73/73 never happened. Fills up to
 * `max` records (end_time = start_time + 5 min) and clears each QSO's
 * bookkeeping like a normal save; returns the count. Drives the Force
 * QSO save button and the automatic flush before the engine is reset
 * (dialog close, FT4/FT8 switch, band change). */
size_t ftx_qso_flush_complete(ftx_qso_record_t *records, size_t max);

/* Drop all internal engine state (manual target, sticky retry, auto-mode
 * blacklist, last-call stickiness and QSO bookkeeping). Call on FT8
 * session start. */
void ftx_qso_reset(void);

/* Drop only the decision state (manual target + sticky, auto blacklist +
 * last-call). The peers ledger survives so an in-progress QSO can still be
 * logged. Call when the operating mode changes under the engine's feet:
 * CQ start, a user click, or an Auto mode switch. */
void ftx_qso_clear_decision_state(void);

#ifdef __cplusplus
}
#endif
