#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <time.h>

typedef enum {
    // "CQ CALL ..." or "CQ DX CALL ..." or "CQ EU CALL ..."
    FTX_MSG_TYPE_CQ,
    // "CALL1 CALL2 GRID"
    FTX_MSG_TYPE_GRID,
    // "CALL1 CALL2 +1"
    FTX_MSG_TYPE_REPORT,
    // "CALL1 CALL2 R+1"
    FTX_MSG_TYPE_R_REPORT,
    // "CALL1 CALL2 RR73"
    FTX_MSG_TYPE_RR73,
    // "CALL1 CALL2 73"
    FTX_MSG_TYPE_73,

    FXT_MSG_TYPE_OTHER,
} ftx_msg_type_t;

typedef struct {
    char           grid[9];
    char           call_de[13];
    int            local_snr;
    int            remote_snr;
    bool           to_me;
    float          freq_hz;
    float          time_sec;
    ftx_msg_type_t type;
} ftx_msg_meta_t;

typedef struct {
    char msg[35];
    int  repeats;
} ftx_tx_msg_t;

/* Engine behaviour selector (the "Auto" button).
 * MANUAL: reply only within the QSO armed by a user click.
 * SNR/DISTANCE/RANDOM: full-auto (ft8d model); the value picks the
 * tie-break used when several candidates share the best QSO progress. */
typedef enum {
    FTX_QSO_MODE_MANUAL = 0,
    FTX_QSO_MODE_SNR,
    FTX_QSO_MODE_DISTANCE,
    FTX_QSO_MODE_RANDOM,
} ftx_qso_mode_t;

typedef struct {
    const char    *local_callsign;
    const char    *local_qth;
    ftx_qso_mode_t mode;
    /* Wall clock of the call (the engine itself never reads the clock);
     * used for QSO start/end timestamps. */
    time_t         now;
} ftx_qso_context_t;

typedef struct {
    const char *text;
    int         snr;
    float       freq_hz;
    float       time_sec;
    bool        odd;
} ftx_decoded_msg_t;

typedef enum {
    FTX_QSO_ACTION_RX = 0,
    FTX_QSO_ACTION_TX,
} ftx_qso_action_t;

/* A completed QSO ready for the logbook. rst_sent is the report we actually
 * transmitted to the peer (matches the peer's log); rst_rcvd is the report
 * the peer gave us. */
typedef struct {
    char   call[13];
    char   grid[9];
    int    rst_sent;
    int    rst_rcvd;
    time_t start_time;
    time_t end_time;
} ftx_qso_record_t;

/* Engine output for exactly one upcoming slot. The caller transmits tx_msg
 * once in the next slot of tx_odd parity and then waits for the next engine
 * response; any retry/repeat policy lives inside the engine.
 *
 * `save` is independent of `action`: a QSO can complete on a received
 * final 73 with no reply scheduled (action stays RX). */
typedef struct {
    ftx_qso_action_t action;
    bool  tx_odd;
    char  tx_msg[35];
    /* Peer frequency for finder cursor / QSY; 0 = keep current. */
    float freq_hz;

    bool             save;
    ftx_qso_record_t qso;
} ftx_qso_response_t;

#ifdef __cplusplus
#include <string>
#include <vector>

std::vector<std::string> split_text(std::string text);

extern "C" {
#endif

void ftx_qso_parse_rx_text(const ftx_qso_context_t *ctx,
                           const char *text, int snr,
                           float freq_hz, float time_sec,
                           ftx_msg_meta_t *meta);

/* Slot-end entry: the complete decoded batch of the slot that just ended
 * (msg_count may be 0 — an empty slot is itself a signal). */
void ftx_qso_on_decoded_messages(const ftx_qso_context_t *ctx,
                                 const ftx_decoded_msg_t *msgs,
                                 size_t msg_count,
                                 bool rx_odd,
                                 ftx_qso_response_t *response);

/* User-click entry: a signal that arms the manual QSO state (target
 * callsign + parity lock + sticky seed) and immediately evaluates the
 * clicked message as a batch of one. Timing (TX window) is the caller's
 * concern; a missed response is regenerated by the sticky retry. */
void ftx_qso_on_user_message(const ftx_qso_context_t *ctx,
                             const char *text,
                             int snr,
                             float freq_hz,
                             bool rx_odd,
                             ftx_qso_response_t *response);

/* Force-save the QSO in progress (manual target, or the last station we
 * transmitted to). Succeeds only when both reports have been exchanged;
 * fills `record` and clears the QSO bookkeeping like a normal save. */
bool ftx_qso_force_save(const ftx_qso_context_t *ctx, ftx_qso_record_t *record);

/* Drop all internal engine state (manual target, sticky retry, auto-mode
 * blacklist, last-call stickiness and QSO bookkeeping). Call on FT8
 * session start. */
void ftx_qso_reset(void);

#ifdef __cplusplus
}
#endif
