name: Cache test
on:
  workflow_dispatch:
  push:
    # Pattern matched against refs/tags
    tags:
      - '**'           # Push events to every tag

jobs:
  build:
    runs-on: ubuntu-22.04
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: false

        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: false
        docker-images: true
        swap-storage: true
    - name: check free space
      run: |
        df -h
        pwd
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout GUI
      uses: actions/checkout@v4
      with:
        submodules: true
        path: x6100_gui

    - name: Checkout buildroot
      uses: actions/checkout@v4
      with:
        submodules: true
        repository: gdyuldin/AetherX6100Buildroot
        path: AetherX6100Buildroot

    - name: Patch GUI mk
      run: |
        sed -i "s,https://github.com/gdyuldin/x6100_gui,${GITHUB_WORKSPACE}/x6100_gui,g" AetherX6100Buildroot/br2_external/package/x6100-gui/x6100_gui.mk
        sed -i "s,^X6100_GUI_SITE_METHOD = git,X6100_GUI_SITE_METHOD = local,g" AetherX6100Buildroot/br2_external/package/x6100-gui/x6100_gui.mk
        sed -i "s,^X6100_GUI_GIT_SUBMODULES,# X6100_GUI_GIT_SUBMODULES,g" AetherX6100Buildroot/br2_external/package/x6100-gui/x6100_gui.mk

    # Configure
    - name: Configure
      run: |
        cd AetherX6100Buildroot && bash ./br_config.sh

    # Ccache
    # - name: Ccache cache files
    #   uses: actions/cache@v4
    #   with:
    #     path: ~/.buildroot-ccache
    #     key: ${{ runner.os }}-ccache-${{ github.sha }}
    #     restore-keys: |
    #       Linux-ccache-${{ github.sha }}
    #       Linux-ccache-
    #       ${{ runner.os }}-ccache-

    - name: Restore Buildroot Cache
      uses: actions/cache/restore@v5
      id: cache-restore
      with:
        path: |
          AetherX6100Buildroot/buildroot_sdk
          ~/.buildroot-ccache
        key: buildroot-cache-
        restore-keys: |
          buildroot-cache-

    - name: Config for SDK
      if: ${{ steps.cache-restore.outputs.cache-matched-key != '' }}
      run: |
        cd AetherX6100Buildroot/build

        echo "=== Switch to External Toolchain ==="
        sed -i '/BR2_TOOLCHAIN_BUILDROOT/d' .config

        # Add external toolchain
        cat << EOF >> .config
        BR2_TOOLCHAIN_EXTERNAL=y
        BR2_TOOLCHAIN_EXTERNAL_CUSTOM=y
        BR2_TOOLCHAIN_EXTERNAL_PATH="${{ github.workspace }}/AetherX6100Buildroot/buildroot_sdk"

        BR2_TOOLCHAIN_EXTERNAL_PREFIX="arm-buildroot-linux-gnueabihf"
        BR2_TOOLCHAIN_EXTERNAL_CUSTOM_PREFIX="arm-buildroot-linux-gnueabihf"

        BR2_TOOLCHAIN_EXTERNAL_GLIBC=y
        BR2_TOOLCHAIN_EXTERNAL_GCC_12=y
        BR2_TOOLCHAIN_EXTERNAL_HEADERS_6_1=y
        BR2_TOOLCHAIN_EXTERNAL_CUSTOM_GLIBC=y
        BR2_TOOLCHAIN_EXTERNAL_HAS_SSP=y
        BR2_TOOLCHAIN_EXTERNAL_HAS_SSP_STRONG=y
        BR2_TOOLCHAIN_EXTERNAL_CXX=y
        BR2_TOOLCHAIN_EXTERNAL_INET_RPC=n

        EOF
        # update config
        make olddefconfig

    # Build
    - name: Build
      run: |
        cd AetherX6100Buildroot/build
        build/host/bin/ccache -M 10G || true  # Limit cache
        make lame
        make mpg123
        make libsndfile-dirclean

        make

    # Replace U-boot
    - name: Replace u-boot
      run: |
        dd if=x6100_gui/u-boot/u-boot-sunxi-with-spl.bin of=AetherX6100Buildroot/build/images/sdcard.img seek=8K bs=1 conv=notrunc

    # Compress image
    - name: Compress image
      run: |
        cd AetherX6100Buildroot/build/images
        mv sdcard.img sdcard.${{ github.ref_name }}.img
        zip sdcard.${{ github.ref_name }}.img.zip sdcard.${{ github.ref_name }}.img

    # Upload image
    # - name: 'Upload image'
    #   uses: actions/upload-artifact@v4
    #   with:
    #     name: sdcard.${{ github.ref_name }}.img
    #     path: AetherX6100Buildroot/build/images/sdcard.${{ github.ref_name }}.img

    # Create release
    # - name: Release
    #   uses: softprops/action-gh-release@v2
    #   if: startsWith(github.ref, 'refs/tags/')
    #   with:
    #     files: AetherX6100Buildroot/build/images/sdcard.${{ github.ref_name }}.img.zip


    - name: Prune Cache
      if: |
        ${{
          success() &&
          github.event_name == 'workflow_dispatch' &&
          github.ref_name == 'main'
        }}
      run: |
        cd AetherX6100Buildroot
        # Get stat
        build/host/bin/ccache -s
        # Prune
        build/host/bin/ccache -c


    - name: Prepare SDK
      if: |
        ${{
          success() &&
          github.event_name == 'workflow_dispatch' &&
          github.ref_name == 'main' &&
          steps.cache-restore.outputs.cache-matched-key == ''
        }}
      run: |
        cd AetherX6100Buildroot/build

        echo "Build SDK..."
        make sdk

        cd ..
        echo "Unpack SDK..."
        mkdir -p buildroot_sdk
        tar -xzf build/images/*_sdk-buildroot.tar.gz -C buildroot_sdk --strip-components=1

    - name: Save Buildroot Cache back to Main
      if: |
        ${{
          success() &&
          github.event_name == 'workflow_dispatch' &&
          github.ref_name == 'main'
        }}
      uses: actions/cache/save@v5
      with:
        path: |
          AetherX6100Buildroot/buildroot_sdk
          ~/.buildroot-ccache
        key: buildroot-cache-${{ github.sha }}
