name: Migrate Old Ccache

on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Restore intermediate ccache
        uses: actions/cache/restore@v4
        with:
          path: ~/.buildroot-ccache
          key: Linux-ccache-86db0f07a4096260b7a7d8a5272bdbde548568f3

      - name: Save via ccache-action
        uses: hendrikmuhs/ccache-action@v1.2
        env:
          CCACHE_DIR: ~/.buildroot-ccache
        with:
          key: ${{ runner.os }}-ccache
